# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TopSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TopSwift
  pod 'Kingfisher', '~> 5.0'

  target 'TopSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TopSwiftUITests' do
    # Pods for testing
  end

end
